<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MusicSpeedChanger</AssemblyName>
    <RootNamespace>MusicSpeedChanger</RootNamespace>
    <Product>Music Speed Changer</Product>
    <Company>Music Speed Changer</Company>
    <Copyright>Copyright © 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Win32Icon>Assets\AppIcon.ico</Win32Icon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\MusicSpeed.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SoundTouch.Net" Version="2.3.2" />
  </ItemGroup>

</Project>
